name: Build .NET App

on:
  push:
    branches:
      - '**'  # Qualquer branch
  schedule:
    - cron: '0 * * * *'  # A cada hora (UTC)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Altere para a versão do seu projeto, ex: '7.0.x', '6.0.x'

      - name: Restaurar dependências
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Testes
        run: dotnet test --no-build --verbosity normal
